# .pre-commit-config.yaml

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  autofix_commit_msg: "style: [pre-commit.ci] auto fixes [...]"
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit, pre-push, manual]
      - id: mixed-line-ending
        name: "Enforce LF newlines on most files"
        args: ["--fix=lf"]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys", "--no-ensure-ascii"]
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        stages: [pre-commit, pre-push, manual]
        types: [yaml]

  # Markdown formatting (Keep this for *.md files)
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-fmt
        name: deno-fmt-md
        files: \.(md|markdown)$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        name: ruff-lint
        args: [
          --fix,
          --exit-non-zero-on-fix,
        ]
        language: python
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: python
        types_or: [python, pyi]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
