[project]
name = "lionagi_dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "tomli>=2.2.1",
]

[dependency-groups]
dev = [
    "khive>=0.3.2",
]
