# Copyright (c) 2023-2026, HaiyangLi <quantocean.li at gmail dot com>
# SPDX-License-Identifier: Apache-2.0
"""Shared models, formatting, team helpers, and worker resolution."""

from __future__ import annotations

from lionagi import FieldModel, json_dumps
from lionagi.models import HashableModel
from lionagi.operations.fields import Instruct

from .._agents import AgentProfile, load_agent_profile
from .._runs import RunDir
from ..team import _now_iso, _save_team

# ── Agent request model (structured output from orchestrator) ─────────────


class AgentRequest(HashableModel):
    """A single agent request generated by the orchestrator."""

    instruct: Instruct
    model: str | None = None


AGENT_REQUEST_FIELDS = FieldModel(list[AgentRequest], name="agents")


# ── Output formatting ─────────────────────────────────────────────────────


def _format_result_text(
    worker_results: list[dict],
    synthesis_result: dict | None = None,
) -> str:
    lines = []
    for i, w in enumerate(worker_results, 1):
        n = len(worker_results)
        lines.append(f"{'═' * 60}")
        lines.append(f"  Worker {i}/{n}  [{w['model']}]")
        lines.append(f"  {w['time_ms']:.0f}ms")
        lines.append(f"{'═' * 60}")
        lines.append(w.get("response", "(no response)"))
        lines.append("")

    if synthesis_result is not None:
        lines.append(f"{'═' * 60}")
        lines.append(f"  Synthesis  [{synthesis_result['model']}]")
        lines.append(f"  {synthesis_result['time_ms']:.0f}ms")
        lines.append(f"{'═' * 60}")
        lines.append(synthesis_result.get("response", "(no response)"))
        lines.append("")

    return "\n".join(lines)


def _format_result_json(
    worker_results: list[dict],
    synthesis_result: dict | None = None,
) -> str:
    out = {"workers": worker_results}
    if synthesis_result is not None:
        out["synthesis"] = synthesis_result
    return json_dumps(out)


# ── Default worker system prompt (shared by flow + fanout) ────────────────


def _bare_worker_system() -> str:
    from lionagi.session.prompts import LION_SYSTEM_MESSAGE
    return LION_SYSTEM_MESSAGE.strip() + "\n\n" + _BARE_WORKER_BODY


_BARE_WORKER_BODY = """\
You are a specialist worker agent in a DAG pipeline. \
Complete your assigned task directly and precisely. \
You may read files, use tools, and run commands as needed. \
Do NOT spawn sub-agents or delegate further — you are a leaf executor.

ARTIFACTS (mandatory): Write all deliverables as files in your current \
working directory. Use the filename specified in your instruction. \
Do NOT print deliverables to stdout — downstream agents read your files. \
Use descriptive filenames (inventory.md, gap_analysis.md), never output.md.

READING UPSTREAM: Your instruction specifies which files to read from \
prior agents using relative paths like ../e1/inventory.md. \
Read those files before starting your analysis.

DOMAIN CONTEXT: If your task domain is unfamiliar, run: \
Q="<task keywords>" && khived lore suggest "$Q" -r <your_role> -l 6

SESSION PERSISTENCE: Your session persists. If given follow-up work \
later, your conversation history is retained.

BASH QUOTING: Use variable assignment for multi-word CLI args: \
Q="your query" && command "$Q" (NOT command "your query").\
"""

BARE_WORKER_SYSTEM = _bare_worker_system()


# ── Team-mode guidance ────────────────────────────────────────────────────

TEAM_WORKER_SYSTEM = """\
You are **{worker_name}**, a specialist on team "{team_name}" (id: {team_id}).

## Your team
{roster_text}

## Team coordination protocol

**Before starting work**: Check your inbox for messages from teammates.
```bash
li team receive -t {team_id} --as {worker_name}
```

**During work**: If you discover something relevant to a teammate, send them a message.
Keep messages short and actionable — coordination signals, not full deliverables.
```bash
li team send "Found 3 undocumented endpoints — hold off on gap analysis until I update inventory" -t {team_id} --to analyst
```

**After work**: Your artifacts (files you write) are the primary deliverable.
Team messages are supplementary context. Results are also auto-posted to the team.

## What goes where
- **Team messages**: coordination signals, warnings, discoveries that affect others
- **Artifact files**: structured deliverables (inventories, analyses, specs, verdicts)
- **stdout**: progress updates only — NOT your deliverable

## Resuming
After this round, teammates or the orchestrator can follow up:
- `li team receive -t {team_id} --as {worker_name}` to read messages
- `li team send "..." -t {team_id} --to {worker_name}` to reply
- `li agent -r {{branch_id}} "follow-up"` to continue your session

Focus on YOUR assignment. Be specific — your output is the deliverable.\
"""


def _create_fanout_team(
    team_name: str,
    worker_names: list[str],
) -> dict:
    from uuid import uuid4

    team_id = uuid4().hex[:12]
    members = ["orchestrator"] + worker_names
    data = {
        "id": team_id,
        "name": team_name,
        "members": members,
        "messages": [],
        "created_at": _now_iso(),
    }
    _save_team(data)
    return data


def _post_results_to_team(
    team_data: dict,
    worker_results: list[dict],
    worker_names: list[str],
    synthesis_result: dict | None = None,
) -> None:
    from uuid import uuid4

    for wr, name in zip(worker_results, worker_names):
        team_data["messages"].append(
            {
                "id": uuid4().hex[:12],
                "from": name,
                "to": ["*"],
                "content": wr.get("response", "(no response)"),
                "timestamp": _now_iso(),
                "read_by": [],
            }
        )

    if synthesis_result:
        team_data["messages"].append(
            {
                "id": uuid4().hex[:12],
                "from": "orchestrator",
                "to": ["*"],
                "content": f"[SYNTHESIS]\n{synthesis_result.get('response', '')}",
                "timestamp": _now_iso(),
                "read_by": [],
            }
        )

    _save_team(team_data)


# ── Worker resolution ────────────────────────────────────────────────────


def _resolve_worker_spec(
    token: str,
) -> tuple[str, AgentProfile | None]:
    """Resolve a worker token to (model_spec, profile_or_None).

    If token contains '/' → model spec (e.g. 'codex/gpt-5.4').
    Otherwise → try loading as agent profile name.
    """
    if "/" in token:
        return token, None
    try:
        profile = load_agent_profile(token)
        return profile.model or "codex/gpt-5.4", profile
    except FileNotFoundError:
        return token, None


def persist_session_branches(
    session, run: RunDir
) -> list[tuple[str, str, str]]:
    """Persist all branches in a session into the run's ``branches/`` dir.

    Returns ``[(provider, branch_id, branch_name)]`` for each branch
    written. Synchronous: each snapshot is a single ``write_text`` and
    there is no gain from async I/O here; removing it also lets callers
    invoke from sync contexts (e.g. timeout-cancel paths).
    """
    run.ensure_state_dirs()
    branch_ids: list[tuple[str, str, str]] = []
    for branch in session.branches:
        provider = branch.chat_model.endpoint.config.provider
        branch_id = str(branch.id)
        run.branch_path(branch_id).write_text(json_dumps(branch.to_dict()))
        branch_ids.append((provider, branch_id, branch.name))
    return branch_ids
