# Copyright (c) 2023-2026, HaiyangLi <quantocean.li at gmail dot com>
# SPDX-License-Identifier: Apache-2.0
"""`li orchestrate fanout` — parallel multi-agent fan-out with optional synthesis.

Three-phase execution:
  1. Orchestrator decomposes task → generates N AgentRequests (instruct + model)
  2. Fan out → each request runs as a communicate node
  3. Synthesis → orchestrator combines all results

Examples:
    # Pattern A: homogeneous, no synthesis
    li o fanout codex/gpt-5.4-xhigh "audit for dead code" -n 3

    # Pattern B: heterogeneous workers, strong model synthesizes
    li o fanout claude/opus-4-6-medium "analyze auth middleware" \\
        --workers "codex/gpt-5.4-high, claude/sonnet, codex/gpt-5.3-codex" \\
        --with-synthesis

    # Pattern C: homogeneous workers, different synthesis model
    li o fanout claude/sonnet "suggest approaches" \\
        -n 3 --with-synthesis claude/opus-4-6-medium
"""

from __future__ import annotations

import argparse
import asyncio
import sys
import time
from pathlib import Path

from lionagi import Branch, FieldModel, Session, iModel, json_dumps
from lionagi.ln import acreate_path
from lionagi.ln.concurrency import run_async
from lionagi.models import HashableModel
from lionagi.operations.builder import OperationGraphBuilder
from lionagi.operations.fields import Instruct
from lionagi.protocols.generic.log import DataLoggerConfig

from ._persistence import LIONAGI_HOME, save_last_branch_pointer
from ._providers import add_common_cli_args, build_imodel_from_spec, parse_model_spec
from .team import _load_team, _now_iso, _save_team, _teams_dir

# ── Agent request model (structured output from orchestrator) ─────────────


class AgentRequest(HashableModel):
    """A single agent request generated by the orchestrator."""

    instruct: Instruct
    model: str | None = None


AGENT_REQUEST_FIELDS = FieldModel(list[AgentRequest], name="agents")


# ── Output formatting ─────────────────────────────────────────────────────


def _format_result_text(
    worker_results: list[dict],
    synthesis_result: dict | None = None,
) -> str:
    lines = []
    for i, w in enumerate(worker_results, 1):
        n = len(worker_results)
        lines.append(f"{'═' * 60}")
        lines.append(f"  Worker {i}/{n}  [{w['model']}]")
        lines.append(f"  {w['time_ms']:.0f}ms")
        lines.append(f"{'═' * 60}")
        lines.append(w.get("response", "(no response)"))
        lines.append("")

    if synthesis_result is not None:
        lines.append(f"{'═' * 60}")
        lines.append(f"  Synthesis  [{synthesis_result['model']}]")
        lines.append(f"  {synthesis_result['time_ms']:.0f}ms")
        lines.append(f"{'═' * 60}")
        lines.append(synthesis_result.get("response", "(no response)"))
        lines.append("")

    return "\n".join(lines)


def _format_result_json(
    worker_results: list[dict],
    synthesis_result: dict | None = None,
) -> str:
    out = {"workers": worker_results}
    if synthesis_result is not None:
        out["synthesis"] = synthesis_result
    return json_dumps(out)


# ── Team-mode guidance ────────────────────────────────────────────────────

TEAM_WORKER_SYSTEM = """\
You are **{worker_name}**, a specialist on team "{team_name}" (id: {team_id}).

## Your team
{roster_text}

## How this works
1. You receive a focused assignment from the orchestrator.
2. Work independently — produce clear, actionable output.
3. Your results are automatically shared with the team via `li team`.
4. After this round, teammates or the orchestrator can follow up:
   - `li team receive -t {team_id} --as {worker_name}` to read messages
   - `li team send "..." -t {team_id} --to {worker_name}` to reply
   - `li agent -r {{branch_id}} "follow-up"` to continue your session

Focus on YOUR assignment. Be specific — your output is the deliverable.\
"""


def _create_fanout_team(
    team_name: str,
    worker_names: list[str],
) -> dict:
    """Create a team for fanout, returning the team data dict."""
    from uuid import uuid4

    team_id = uuid4().hex[:12]
    members = ["orchestrator"] + worker_names
    data = {
        "id": team_id,
        "name": team_name,
        "members": members,
        "messages": [],
        "created_at": _now_iso(),
    }
    _save_team(data)
    return data


def _post_results_to_team(
    team_data: dict,
    worker_results: list[dict],
    worker_names: list[str],
    synthesis_result: dict | None = None,
) -> None:
    """Post worker outputs and synthesis as team messages."""
    from uuid import uuid4

    for wr, name in zip(worker_results, worker_names):
        team_data["messages"].append(
            {
                "id": uuid4().hex[:12],
                "from": name,
                "to": ["*"],
                "content": wr.get("response", "(no response)"),
                "timestamp": _now_iso(),
                "read_by": [],
            }
        )

    if synthesis_result:
        team_data["messages"].append(
            {
                "id": uuid4().hex[:12],
                "from": "orchestrator",
                "to": ["*"],
                "content": f"[SYNTHESIS]\n{synthesis_result.get('response', '')}",
                "timestamp": _now_iso(),
                "read_by": [],
            }
        )

    _save_team(team_data)


# ── Core fanout execution ─────────────────────────────────────────────────


async def _run_fanout(
    model_spec: str,
    prompt: str,
    *,
    num_workers: int = 3,
    workers_str: str | None = None,
    with_synthesis: bool = False,
    synthesis_model: str | None = None,
    synthesis_prompt: str | None = None,
    max_concurrent: int = 0,
    yolo: bool = False,
    verbose: bool = False,
    effort: str | None = None,
    theme: str | None = None,
    output_format: str = "text",
    save_dir: str | None = None,
    team_name: str | None = None,
    cwd: str | None = None,
    timeout: int | None = None,
) -> str:
    """Three-phase fan-out: decompose → fan out → synthesize."""
    t0 = time.monotonic()

    # Build orchestrator model
    orc_imodel = build_imodel_from_spec(
        model_spec,
        yolo=yolo,
        verbose=verbose,
        effort_override=effort,
        theme=theme,
    )

    # Determine available worker models for the orchestrator's guidance
    if workers_str:
        worker_model_list = [s.strip() for s in workers_str.split(",")]
    else:
        ms = parse_model_spec(model_spec)
        worker_model_list = [ms.model] * num_workers

    # ── Team setup (if --team-mode) ─────────────────────────────────
    team_data = None
    worker_names = [f"worker-{i+1}" for i in range(len(worker_model_list))]
    if team_name:
        team_data = _create_fanout_team(team_name, worker_names)
        if not verbose:
            print(
                f"Team '{team_name}' created ({team_data['id']}): "
                f"{', '.join(worker_names)}",
                file=sys.stderr,
            )

    # Apply cwd to endpoint if specified
    if cwd:
        orc_imodel.endpoint.config.kwargs.setdefault("repo", Path(cwd))

    # ── Phase 1: Orchestrator decomposes task ─────────────────────────
    builder = OperationGraphBuilder("Fanout")
    orc_branch = Branch(
        chat_model=orc_imodel,
        log_config=DataLoggerConfig(auto_save_on_exit=False),
        name="orchestrator",
    )
    session = Session(default_branch=orc_branch)

    models_guidance = ", ".join(worker_model_list)
    root = builder.add_operation(
        "operate",
        branch=orc_branch,
        instruct=Instruct(
            instruction=(
                f"Generate {len(worker_model_list)} agent requests to address "
                f"the following task. Each agent should tackle a distinct angle "
                f"or perspective. Each agent is a WORKER that will DIRECTLY "
                f"answer its assigned sub-task — NOT delegate further."
            ),
            context={"user_prompt": prompt},
            guidance=(
                f"Available worker models: {models_guidance}. "
                f"IMPORTANT: Each AgentRequest instruction must be a DIRECT "
                f"task the worker will answer itself — not a meta-instruction "
                f"to generate more agents or decompose further. Workers are "
                f"leaf executors, not orchestrators. "
                f"Set actions=false and reason=false in every instruct — "
                f"workers must NOT use tools, spawn agents, or read files. "
                f"They answer from their own knowledge only. "
                f"If multiple models are provided, set the model field to "
                f"the exact model string from the list above. "
                f"If all workers use the same model, model can be null."
            ),
        ),
        field_models=[AGENT_REQUEST_FIELDS],
        reason=True,
    )

    if not verbose:
        print(
            f"Phase 1: Orchestrator decomposing task into "
            f"{len(worker_model_list)} agent requests...",
            file=sys.stderr,
        )

    result1 = await session.flow(builder.get_graph())
    t_decompose = time.monotonic() - t0

    # Extract agent requests
    root_result = result1.get("operation_results", {}).get(root)
    agents: list[AgentRequest] = getattr(root_result, "agents", None) or []

    if not agents:
        return "Orchestrator produced no agent requests."

    if not verbose:
        print(
            f"Phase 1 done ({t_decompose:.1f}s): {len(agents)} requests generated.",
            file=sys.stderr,
        )

    # ── Phase 2: Fan out ──────────────────────────────────────────────
    default_ms = parse_model_spec(model_spec)
    fanned_nodes = []
    fanned_labels = []

    for i, a in enumerate(agents):
        worker_model = a.model or default_ms.model
        worker_imodel = build_imodel_from_spec(
            worker_model,
            yolo=yolo,
            verbose=verbose,
            effort_override=effort,
            theme=theme,
        )
        if cwd:
            worker_imodel.endpoint.config.kwargs.setdefault("repo", Path(cwd))
        wname = worker_names[i]
        if team_data:
            teammates = [n for n in worker_names if n != wname]
            roster_lines = [f"- orchestrator (coordinator)"]
            roster_lines += [f"- {t}" for t in teammates]
            roster_lines.append(f"- **{wname}** (you)")
            worker_system = TEAM_WORKER_SYSTEM.format(
                worker_name=wname,
                team_name=team_data["name"],
                team_id=team_data["id"],
                roster_text="\n".join(roster_lines),
            )
        else:
            worker_system = (
                "You are a leaf worker agent. Answer the instruction directly "
                "from your own knowledge. Do NOT spawn sub-agents, use tools, "
                "or read files. Just answer concisely."
            )
        worker_branch = Branch(
            chat_model=worker_imodel,
            system=worker_system,
            log_config=DataLoggerConfig(auto_save_on_exit=False),
            name=wname,
        )
        session.include_branches(worker_branch)
        worker_context = [
            {"overall_task": prompt},
            a.instruct.context or "",
        ]
        node = builder.add_operation(
            "communicate",
            branch=worker_branch,
            depends_on=[root],
            instruction=a.instruct.instruction,
            guidance=a.instruct.guidance,
            context=worker_context,
        )
        fanned_nodes.append(node)
        fanned_labels.append(worker_model)

    if not verbose:
        labels = ", ".join(fanned_labels)
        print(
            f"Phase 2: Fanning out to {len(fanned_nodes)} workers: [{labels}]",
            file=sys.stderr,
        )

    t1 = time.monotonic()
    conc = max_concurrent if max_concurrent > 0 else len(fanned_nodes)
    result2 = await session.flow(
        builder.get_graph(),
        max_concurrent=conc,
        verbose=verbose,
    )
    t_fanout = time.monotonic() - t1

    # Collect results
    op_results = result2.get("operation_results", {})
    worker_results = []
    contexts = []
    for i, nid in enumerate(fanned_nodes):
        res = op_results.get(nid)
        response_text = str(res) if res is not None else "(no response)"
        worker_results.append(
            {
                "worker": i + 1,
                "model": fanned_labels[i],
                "response": response_text,
                "time_ms": t_fanout * 1000,
            }
        )
        contexts.append(response_text)

    if not verbose:
        print(f"Phase 2 done ({t_fanout:.1f}s).", file=sys.stderr)

    # ── Phase 3: Synthesis ────────────────────────────────────────────
    synthesis_result = None
    if with_synthesis and contexts:
        synth_spec = synthesis_model or model_spec
        synth_label = str(parse_model_spec(synth_spec))

        if not verbose:
            print(f"Phase 3: Synthesis [{synth_label}]...", file=sys.stderr)

        synth_instruction = synthesis_prompt or (
            f"Synthesize the following {len(contexts)} worker responses "
            f"into a cohesive analysis.\n\n"
            f"Original task: {prompt}"
        )

        synth_node = builder.add_operation(
            "communicate",
            branch=orc_branch,
            depends_on=fanned_nodes,
            instruction=synth_instruction,
            context=contexts,
        )

        t2 = time.monotonic()
        result3 = await session.flow(builder.get_graph(), verbose=verbose)
        t_synth = time.monotonic() - t2

        synth_res = result3.get("operation_results", {}).get(synth_node)
        synthesis_result = {
            "model": synth_label,
            "response": str(synth_res) if synth_res is not None else "(no response)",
            "time_ms": t_synth * 1000,
        }

        if not verbose:
            print(f"Phase 3 done ({t_synth:.1f}s).", file=sys.stderr)

    # ── Output ────────────────────────────────────────────────────────
    if output_format == "json":
        output = _format_result_json(worker_results, synthesis_result)
    else:
        output = _format_result_text(worker_results, synthesis_result)

    # ── Save ──────────────────────────────────────────────────────────
    if save_dir:
        save_path = Path(save_dir)
        save_path.mkdir(parents=True, exist_ok=True)
        for wr in worker_results:
            p = save_path / f"worker_{wr['worker']}.md"
            p.write_text(wr["response"])
        if synthesis_result:
            (save_path / "synthesis.md").write_text(synthesis_result["response"])
        meta = {
            "prompt": prompt,
            "workers": fanned_labels,
            "synthesis_model": synthesis_result["model"] if synthesis_result else None,
            "total_time_ms": (time.monotonic() - t0) * 1000,
        }
        (save_path / "meta.json").write_text(json_dumps(meta))
        if not verbose:
            print(f"Saved to {save_path}", file=sys.stderr)

    # ── Post to team ─────────────────────────────────────────────────
    if team_data:
        _post_results_to_team(team_data, worker_results, worker_names, synthesis_result)
        if not verbose:
            print(
                f"\nTeam '{team_data['name']}' ({team_data['id']}): "
                f"{len(worker_results)} results posted.",
                file=sys.stderr,
            )
            print(
                f"  li team receive -t {team_data['id']} --as orchestrator",
                file=sys.stderr,
            )
            print(
                f"  li team show {team_data['id']}",
                file=sys.stderr,
            )

    # ── Persist all branches ─────────────────────────────────────────
    orc_provider = orc_branch.chat_model.endpoint.config.provider
    orc_branch_id = str(orc_branch.id)

    # Save orchestrator
    orc_path = await acreate_path(
        directory=LIONAGI_HOME / "logs" / "agents" / orc_provider,
        filename=orc_branch_id,
        file_exist_ok=True,
    )
    await orc_path.write_text(json_dumps(orc_branch.to_dict()))
    save_last_branch_pointer(orc_provider, orc_branch_id)

    # Save all worker branches (everything in session except orchestrator)
    worker_branch_ids = []
    for branch in session.branches:
        if str(branch.id) == orc_branch_id:
            continue
        w_provider = branch.chat_model.endpoint.config.provider
        w_branch_id = str(branch.id)
        w_path = await acreate_path(
            directory=LIONAGI_HOME / "logs" / "agents" / w_provider,
            filename=w_branch_id,
            file_exist_ok=True,
        )
        await w_path.write_text(json_dumps(branch.to_dict()))
        worker_branch_ids.append((w_provider, w_branch_id))

    t_total = time.monotonic() - t0
    if not verbose:
        print(f"\nTotal: {t_total:.1f}s", file=sys.stderr)

    print(f'\n[orchestrator] li agent -r {orc_branch_id} "..."', file=sys.stderr)
    for i, (wp, wid) in enumerate(worker_branch_ids):
        print(f'[worker-{i+1}]      li agent -r {wid} "..."', file=sys.stderr)

    return output


# ── CLI registration ──────────────────────────────────────────────────────


def add_orchestrate_subparser(subparsers: argparse._SubParsersAction) -> None:
    """Register `li orchestrate` (alias `li o`) with its sub-commands."""
    orch = subparsers.add_parser(
        "orchestrate",
        aliases=["o"],
        help="Multi-agent orchestration patterns.",
        description="Orchestrate multiple agents in structured patterns.",
    )
    orch_sub = orch.add_subparsers(dest="orch_command", required=True)

    fo = orch_sub.add_parser(
        "fanout",
        help="Fan-out N workers in parallel, optionally synthesize.",
        description=(
            "Orchestrator decomposes task into N agent requests, "
            "fans out to workers, optionally synthesizes. "
            "Effort can be embedded in model spec: claude/opus-4-7-high."
        ),
    )
    fo.add_argument(
        "model",
        help=(
            "Orchestrator model spec (provider/model-effort). "
            "Also used as default worker model unless --workers specified."
        ),
    )
    fo.add_argument("prompt", help="Task prompt for the orchestrator to decompose.")

    fo.add_argument(
        "-n",
        "--num-workers",
        type=int,
        default=3,
        help="Number of workers (default: 3). Ignored if --workers set.",
    )
    fo.add_argument(
        "--workers",
        metavar="M1,M2,...",
        default=None,
        help="Comma-separated worker model specs (each can include effort).",
    )
    fo.add_argument(
        "--max-concurrent",
        type=int,
        default=0,
        help="Max concurrent workers (default: all).",
    )
    fo.add_argument(
        "--with-synthesis",
        nargs="?",
        const=True,
        default=False,
        metavar="MODEL",
        help="Enable synthesis. Bare flag uses orchestrator model; with arg uses that model.",
    )
    fo.add_argument(
        "--synthesis-prompt",
        default=None,
        help="Custom synthesis instruction.",
    )
    fo.add_argument(
        "--output",
        choices=("text", "json"),
        default="text",
        help="Output format (default: text).",
    )
    fo.add_argument(
        "--save",
        metavar="DIR",
        default=None,
        help="Save outputs to directory.",
    )

    fo.add_argument(
        "--team-mode",
        nargs="?",
        const="fanout",
        default=None,
        metavar="NAME",
        help=(
            "Create a persistent team for this fanout. Workers get team context "
            "and results are posted as team messages. Bare flag uses 'fanout' as "
            "team name; with arg uses that name."
        ),
    )

    add_common_cli_args(fo)


def run_orchestrate(args: argparse.Namespace) -> int:
    """Dispatch orchestrate sub-commands."""
    if args.orch_command == "fanout":
        synth = args.with_synthesis
        with_synthesis = synth is not False
        synthesis_model = synth if isinstance(synth, str) else None

        try:
            output = run_async(
                _run_fanout(
                    model_spec=args.model,
                    prompt=args.prompt,
                    num_workers=args.num_workers,
                    workers_str=args.workers,
                    with_synthesis=with_synthesis,
                    synthesis_model=synthesis_model,
                    synthesis_prompt=args.synthesis_prompt,
                    max_concurrent=args.max_concurrent,
                    yolo=args.yolo,
                    verbose=args.verbose,
                    effort=args.effort,
                    theme=args.theme,
                    output_format=args.output,
                    save_dir=args.save,
                    team_name=args.team_mode,
                    cwd=args.cwd,
                    timeout=args.timeout,
                )
            )
        except asyncio.TimeoutError:
            print(
                f"Orchestration timed out after {args.timeout}s",
                file=sys.stderr,
            )
            return 1
        if not args.verbose:
            print(output)
        return 0

    print(f"Unknown orchestrate command: {args.orch_command}", file=sys.stderr)
    return 1
